version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    entrypoint: sh -c "pip install -r requirements.txt && /bin/sh"
    working_dir: /var/www/app
    volumes:
      - type: bind
        source: .
        target: /var/www/app
    tty: true
